# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d6d20d47effb89e808d021edf3e6e0ab558be3d84b09a47a187a4dfeceb11f0fdefc22a06d172c4b9533671e24c6930e4fb5b825507b48b714e644bff7e7087

test:
  secret_key_base: 19bc72db2c690e55491dc56805caae8077a86711355274dd7a8787cb8e2670e23b7bfc128099552a65ea6391c7b930c0c888913dbd8e5d8a961a26442eb0caae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
